<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PublishSingleFile>true</PublishSingleFile>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Frosty.Modding\Frosty.Modding.csproj"/>
    <ProjectReference Include="..\Frosty.Sdk\Frosty.Sdk.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <None Update="Profiles\*.json" CopyToOutputDirectory="PreserveNewest"/>
    <None Update="Sdk\Strings\*.json" CopyToOutputDirectory="PreserveNewest"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Pastel"/>
    <PackageReference Include="Sharprompt"/>
    <PackageReference Include="System.CommandLine"/>
  </ItemGroup>
</Project>
