<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <PublishSingleFile>true</PublishSingleFile>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>


    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Controls.TreeDataGrid" />
        <PackageReference Include="Avalonia.Desktop" />
        <PackageReference Include="Avalonia.Themes.Fluent" />
        <PackageReference Include="Avalonia.Fonts.Inter" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" />
        <PackageReference Include="CommunityToolkit.Mvvm" />
        <PackageReference Include="MessageBox.Avalonia" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
        <PackageReference Include="Pastel" />
    </ItemGroup>


    <ItemGroup>
      <ProjectReference Include="..\Frosty.Sdk\Frosty.Sdk.csproj" />
    </ItemGroup>


    <ItemGroup>
      <None Update="Sdk\*.dll" CopyToOutputDirectory="PreserveNewest" />
      <None Update="Profiles\*.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
</Project>
