<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="TestData\new_huffman"/>
    <None Remove="TestData\original_huffman"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Frosty.Sdk\Frosty.Sdk.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="NUnit"/>
    <PackageReference Include="NUnit3TestAdapter"/>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="TestData\new_huffman">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CustomToolNamespace>FrostySdkTest</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Include="TestData\original_huffman">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CustomToolNamespace>FrostySdkTest</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>

</Project>
